/* =====================================================================
   ARAYI — ԿԱՅՔԻ ՏԵՔՍՏԵՐԸ (հայերեն և անգլերեն)
   Տեքստ փոխելու համար գտեք անհրաժեշտ տողը և փոխեք չակերտների ներսը։
   Կապի տվյալները (հեռախոս, էլ. փոստ, սոցցանցեր) այստեղ ՉԵՆ.
   դրանք գտնվում են js/config.js ֆայլում։
   ===================================================================== */

window.CONTENT = {
  hy: {
    "meta.title": "ARAYI — Անշարժ գույք, ներմուծում և բիզնես | Եղվարդ",
    "meta.description": "ARAYI. անշարժ գույքի առք, վաճառք և վարձակալություն Եղվարդում և Կոտայքում, ներմուծում աշխարհի տարբեր երկրներից և բիզնեսի գործարկում՝ սկզբից մինչև վերջ։",

    "skip": "Անցնել բովանդակությանը",
    "nav.services": "Ծառայություններ",
    "nav.import": "Ներմուծում",
    "nav.process": "Ինչպես ենք աշխատում",
    "nav.contact": "Կապ",
    "nav.menu": "Մենյու",
    "brand.name": "ԱՐԱՅԻ",

    "hero.title": "Անշարժ գույք, ներմուծում և բիզնեսի գործարկում՝ մեկ վստահելի գործընկերից",
    "hero.text": "ARAYI-ն Եղվարդում գործող ընկերություն է։ Օգնում ենք գնել, վաճառել և վարձակալել գույք, ներմուծել ապրանքներ աշխարհի տարբեր երկրներից և ստեղծել ու կայունացնել ձեր բիզնեսը՝ սկզբից մինչև վերջ։",
    "hero.call": "Զանգահարել",
    "hero.whatsapp": "Գրել WhatsApp-ով",
    "hero.place": "Եղվարդ, Կոտայքի մարզ",
    "hero.img": "ARAYI գրասենյակի ցուցափեղկը՝ լոգոյով",

    "services.title": "Ինչով ենք զբաղվում",
    "services.lead": "Երեք ուղղություն, որոնք լրացնում են իրար. կարող եք դիմել մեկի համար կամ վստահել ամբողջ գործընթացը։",
    "s1.title": "Անշարժ գույք",
    "s1.text": "Առք, վաճառք և վարձակալություն Եղվարդում, Կոտայքում և Երևանում։",
    "s1.b1": "Գույքի որոնում և գնահատում",
    "s1.b2": "Փաստաթղթերի ստուգում և գործարքի ուղեկցում",
    "s1.b3": "Վարձակալություն և գույքի կառավարում",
    "s2.title": "Ներմուծում աշխարհից",
    "s2.text": "Ապրանքներ և սարքավորումներ ԱՄՆ-ից, Եվրոպայից, Չինաստանից և այլ երկրներից։",
    "s2.b1": "Մատակարարի որոնում և ստուգում",
    "s2.b2": "Որակի ստուգում մինչև բեռնումը",
    "s2.b3": "Լոգիստիկա, մաքսազերծում և առաքում",
    "s3.title": "Բիզնեսի ստեղծում և կայունացում",
    "s3.text": "Նոր բիզնեսի գործարկում և աջակցություն առաջին ամիսներին։",
    "s3.b1": "Տարածքի և սարքավորումների ընտրություն",
    "s3.b2": "Գործարկման պլան և բյուջե",
    "s3.b3": "Ուղեկցում՝ մինչև բիզնեսը կայունանա",

    "import.title": "Ներմուծում աշխարհի տարբեր երկրներից",
    "import.text": "Գտնում ենք մատակարարին, ստուգում ենք ապրանքը և հասցնում ենք այն մինչև ձեր դուռը։ Ընտրում ենք ճանապարհը՝ ըստ ձեր բյուջեի և ժամկետի։",
    "import.map": "Աշխարհի քարտեզ՝ երթուղիներով դեպի Հայաստան, Եղվարդ",
    "import.countries": "Երկրներ, որտեղից ներմուծում ենք",
    "c.us": "ԱՄՆ", "c.br": "Բրազիլիա", "c.eu": "Եվրոպա", "c.ru": "Ռուսաստան",
    "c.cn": "Չինաստան", "c.ir": "Իրան", "c.ae": "ԱՄԷ", "c.eg": "Եգիպտոս",
    "import.modes": "Ինչ ենք անում ձեր փոխարեն",
    "m.air": "Օդային փոխադրում",
    "m.sea": "Ծովային փոխադրում",
    "m.land": "Ցամաքային և երկաթուղային փոխադրում",
    "m.ware": "Պահեստավորում",
    "m.customs": "Մաքսային ձևակերպում",
    "import.transport": "Ինքնաթիռ, նավ, գնացք և բեռնատար՝ Արարատի ֆոնին",

    "process.title": "Ինչպես ենք աշխատում",
    "p1.title": "Հայտ", "p1.text": "Պատմում եք, թե ինչ է պետք. գույք, ապրանք կամ բիզնեսի գաղափար։",
    "p2.title": "Հաշվարկ", "p2.text": "Պատրաստում ենք առաջարկ՝ հստակ գներով և ժամկետներով։",
    "p3.title": "Պայմանագիր", "p3.text": "Ամեն ինչ ամրագրում ենք գրավոր՝ առանց թաքնված վճարների։",
    "p4.title": "Կատարում", "p4.text": "Կատարում ենք աշխատանքը և պարբերաբար տեղեկացնում ընթացքի մասին։",
    "p5.title": "Արդյունք", "p5.text": "Ստանում եք գույքը, ապրանքը կամ գործող բիզնեսը։",

    "estate.title": "Գույք Եղվարդում և Կոտայքում",
    "estate.text": "Գիտենք տեղական շուկան և կօգնենք գտնել ճիշտ գույքը ճիշտ գնով։ Ստուգում ենք փաստաթղթերը և ուղեկցում ենք գործարքը մինչև կադաստրային գրանցում։",
    "estate.img": "Ժամանակակից առանձնատուն այգով",

    "why.title": "Ինչու ARAYI",
    "w1.title": "Վստահելի գործընկերներ", "w1.text": "Ստուգված մատակարարներ և գործընկերներ Հայաստանում և արտերկրում։",
    "w2.title": "Ամբողջական սպասարկում", "w2.text": "Ամեն ինչ անում ենք մենք, որպեսզի դուք չանեք։",
    "w3.title": "Միշտ ժամանակին", "w3.text": "Հստակ ժամկետներ և պարբերական հաշվետվություն։",
    "w4.title": "Ապահով և հուսալի", "w4.text": "Ձեր բեռը և գործարքը մեր պատասխանատվությունն են։",

    "contact.title": "Կապ մեզ հետ",
    "contact.text": "Զանգահարեք, գրեք կամ այցելեք մեր գրասենյակ։ Առաջին խորհրդատվությունն անվճար է։",
    "contact.phone": "Հեռախոս",
    "contact.email": "Էլ. փոստ",
    "contact.whatsapp": "WhatsApp",
    "contact.address": "Հասցե",
    "contact.hours": "Աշխատանքային ժամեր",
    "contact.social": "Մենք սոցցանցերում",
    "contact.map": "Քարտեզ՝ ARAYI գրասենյակի տեղադրությամբ",

    "footer.tagline": "Անշարժ գույք • Ներմուծում • Բիզնես",
    "footer.rights": "Բոլոր իրավունքները պաշտպանված են։",
    "footer.top": "Վերև"
  },

  en: {
    "meta.title": "ARAYI — Real Estate, Import and Business | Yeghvard, Armenia",
    "meta.description": "ARAYI: buying, selling and renting property in Yeghvard and Kotayk, importing goods from around the world, and launching businesses from start to finish.",

    "skip": "Skip to content",
    "nav.services": "Services",
    "nav.import": "Import",
    "nav.process": "How we work",
    "nav.contact": "Contact",
    "nav.menu": "Menu",
    "brand.name": "ARAYI",

    "hero.title": "Real estate, import and business launch from one trusted partner",
    "hero.text": "ARAYI is a company based in Yeghvard, Armenia. We help you buy, sell and rent property, import goods from around the world, and build and stabilize your business from start to finish.",
    "hero.call": "Call us",
    "hero.whatsapp": "Message on WhatsApp",
    "hero.place": "Yeghvard, Kotayk Province",
    "hero.img": "ARAYI office storefront with the logo",

    "services.title": "What we do",
    "services.lead": "Three services that support each other. Come to us for one, or trust us with the whole process.",
    "s1.title": "Real estate",
    "s1.text": "Buying, selling and renting in Yeghvard, Kotayk and Yerevan.",
    "s1.b1": "Property search and valuation",
    "s1.b2": "Document checks and deal support",
    "s1.b3": "Rentals and property management",
    "s2.title": "Worldwide import",
    "s2.text": "Goods and equipment from the USA, Europe, China and other countries.",
    "s2.b1": "Finding and verifying suppliers",
    "s2.b2": "Quality inspection before shipping",
    "s2.b3": "Logistics, customs clearance and delivery",
    "s3.title": "Business launch and stabilization",
    "s3.text": "Launching a new business and supporting it through the first months.",
    "s3.b1": "Choosing premises and equipment",
    "s3.b2": "Launch plan and budget",
    "s3.b3": "Support until the business is stable",

    "import.title": "Import from around the world",
    "import.text": "We find the supplier, check the goods and deliver them to your door. We choose the route that fits your budget and deadline.",
    "import.map": "World map with routes to Yeghvard, Armenia",
    "import.countries": "Countries we import from",
    "c.us": "USA", "c.br": "Brazil", "c.eu": "Europe", "c.ru": "Russia",
    "c.cn": "China", "c.ir": "Iran", "c.ae": "UAE", "c.eg": "Egypt",
    "import.modes": "What we handle for you",
    "m.air": "Air freight",
    "m.sea": "Sea freight",
    "m.land": "Road and rail transport",
    "m.ware": "Warehousing",
    "m.customs": "Customs clearance",
    "import.transport": "Airplane, ship, train and truck with Mount Ararat behind",

    "process.title": "How we work",
    "p1.title": "Request", "p1.text": "Tell us what you need: a property, goods or a business idea.",
    "p2.title": "Estimate", "p2.text": "We prepare an offer with clear prices and deadlines.",
    "p3.title": "Contract", "p3.text": "Everything is agreed in writing, with no hidden fees.",
    "p4.title": "Delivery", "p4.text": "We do the work and keep you updated along the way.",
    "p5.title": "Result", "p5.text": "You receive the property, the goods or a working business.",

    "estate.title": "Property in Yeghvard and Kotayk",
    "estate.text": "We know the local market and will help you find the right property at the right price. We check the documents and support the deal through to cadastre registration.",
    "estate.img": "Modern house with a garden",

    "why.title": "Why ARAYI",
    "w1.title": "Reliable partners", "w1.text": "Verified suppliers and partners in Armenia and abroad.",
    "w2.title": "End-to-end service", "w2.text": "We handle everything so you don't have to.",
    "w3.title": "On time, every time", "w3.text": "Clear deadlines and regular updates.",
    "w4.title": "Safe and secure", "w4.text": "Your cargo and your deal are our responsibility.",

    "contact.title": "Contact us",
    "contact.text": "Call, write or visit our office. Your first consultation is free.",
    "contact.phone": "Phone",
    "contact.email": "Email",
    "contact.whatsapp": "WhatsApp",
    "contact.address": "Address",
    "contact.hours": "Opening hours",
    "contact.social": "Follow us",
    "contact.map": "Map showing the ARAYI office location",

    "footer.tagline": "Real estate • Import • Business",
    "footer.rights": "All rights reserved.",
    "footer.top": "Back to top"
  }
};
